# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop
- qa
- master
- hotfix
- uat
jobs: 
- job: PrimerJob 
  pool: 
    vmImage: 'ubuntu-latest' 
  steps:   
  - task: NodeTool@0 
    displayName: 'Use Node 14.x' 
    inputs: 
      versionSpec: 14.x
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: api' 
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'api'
      publishLocation: 'Container'        
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud'
      organization: 'ab-inbev-las'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: '$(NombreApp)'
      cliProjectName: 'ABI-Bolt-API-Shopping'
      cliSources: '.'
      extraProperties: 'sonar.exclusions=**/upload/**,**/src/**,**/manifest/**,**/src/shared/**,**/src/shared/**/**,**/src/shared/legacy/**,**/jest.*.js,**/test/**,**/src/planillarecepcion/**,**/src/planillaarmado/**,**/src/planilladespacho/**,**/src/carrito/**,**/src/producto/**,**/src/pallet/**,**/src/ordentransporte/**'
  - script: |
      npm config set registry https://verdaccio.proguidemc.com
      npm install
      npm run test
    displayName: 'npm install and test'
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml'
  - task: Npm@1 
    displayName: 'npm custom' 
    inputs: 
      command: custom 
      verbose: false 
      customCommand: 'install -g @cyclonedx/bom@3.10.6'
  - task: CmdLine@2 
    displayName: 'Create BOM file' 
    inputs: 
      script: 'cyclonedx-bom -d -o $(Build.Repository.LocalPath)/bom.xml'
  - task: PublishBuildArtifacts@1 
    displayName: 'Publish Artifact: drop' 
    inputs: 
      PathtoPublish: '$(Build.Repository.LocalPath)/bom.xml'
- job: SegundoJob 
  dependsOn: PrimerJob 
  condition: succeeded('PrimerJob') 
  pool: 
    name: 'LAS Pipelines (AKS)' 
  steps: 
  - task: DownloadBuildArtifacts@1 
    displayName: 'Download Build Artifacts' 
    inputs: 
      artifactName: drop 
      itemPattern: 'drop/**'
  - task: Bash@3 
    displayName: 'Upload BOM' 
    inputs: 
      targetType: 'inline' 
      script: | 
        if [[ $(BranchName) == "develop" || $(BranchName) == "master" ]]; then
          curl -X "POST" "https://dependency-track.abinbev-las.com/api/v1/bom" -H 'X-Api-Key: $(apikeydtrack)' -F 'projectName=$(NombreApp)' -F 'autoCreate=true' -F 'projectVersion=$(BranchName)' -F 'bom=@$(System.ArtifactsDirectory)/drop/bom.xml' 
        else 
          curl -X "POST" "https://dependency-track.abinbev-las.com/api/v1/bom" -H 'X-Api-Key: $(apikeydtrack)' -F 'projectName=$(NombreApp)' -F 'autoCreate=true' -F 'projectVersion=latest' -F 'bom=@$(System.ArtifactsDirectory)/drop/bom.xml'
        fi
  - task: Bash@3 
    displayName: 'UUID Extraction' 
    inputs: 
      targetType: 'inline' 
      script: | 
        if [[ $(BranchName) == "develop" || $(BranchName) == "master" ]]; then
          uuid=$(curl -H 'X-Api-Key: $(apikeydtrack)' -ks https://dependency-track.abinbev-las.com/api/v1/project/lookup\?name\=$(NombreApp)\&version\=$(BranchName) | jq -r '.uuid') 
        else 
          uuid=$(curl -H 'X-Api-Key: $(apikeydtrack)' -ks https://dependency-track.abinbev-las.com/api/v1/project/lookup\?name\=$(NombreApp)\&version\=latest | jq -r '.uuid') 
        fi 
        echo "##vso[task.setvariable variable=uuid]$uuid"
  - task: upload-bom-dtrack-task@1 
    inputs: 
      bomFilePath: '$(System.ArtifactsDirectory)/drop/bom.xml' 
      dtrackProjId: '$(uuid)' 
      dtrackAPIKey: '$(apikeydtrack)' 
      dtrackURI: 'https://dependency-track.abinbev-las.com' 
      thresholdAction: 'error' 
      thresholdCritical: '-1' 
      thresholdHigh: '-1' 
      thresholdMedium: '-1' 
      thresholdLow: '-1' 
      thresholdUnassigned: '-1'
